url: http://jsonapi.org
safe: true
lsi: false
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
  - ./vendor
  - vendor
  - ./bundle/vendor
  - bundle/vendor
  - config.ru
  - Gemfile
  - Gemfile.lock

markdown: redcarpet
pygments: false
port: 9876

navigation:
- title: Format
  url: /format/
- title: Extensions
  url: /extensions/
- title: Recommendations
  url: /recommendations/
- title: Implementations
  url: /implementations/
- title: FAQ
  url: /faq/
- title: About
  url: /about/
